---
title: Clean aggregation 3 data
author: Shir Dekel
date: '`r format(Sys.time())`'
output_format: html_document
vignette: >
  %\VignetteIndexEntry{Clean aggregation 3 data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

Load packages and functions

```{r}
source(DataPackageR::project_path("packages.R"))
project_path("R") %>%
  list.files(full.names = TRUE) %>%
  lapply(source)
```

Clean data

```{r}
data_raw <-
  project_extdata_path("qualtrics") %>%
      list.files(full.names = TRUE) %>%
      map_dfr(~ .x %>%
          read_csv(col_types = cols()))

reference_doc <-
  get_reference_doc()

reference_doc_split <-
  get_reference_doc_split(reference_doc)

dv_match <-
  get_dv_match(reference_doc_split)

data <-
  data_raw %>%
  filter_masters() %>%
  rename_masters(dv_match) %>%
  pivot_masters() %>%
  select(
    recorded_date,
    response_id,
    duration_in_seconds,
    business_edu,
    business_edu_other,
    business_exp,
    order_b:npv_knowledge
  ) %>%
  mutate(
    across(business_edu, recode_business_edu),
    across(business_exp, recode_business_exp),
    across(reliability_amount, recode_reliability_masters),
    across(where(shirthesis::check_numeric), as.numeric),
    project = recode_project_masters(project, order),
    npv_amount = get_npv_amount(project),
    across(c(product, project, alignment, reliability_amount), as.factor),
    sample = "masters"
  ) %>%
  shirthesis::add_id_column(response_id) %>%
  get_npv_allocation_correlation() %>%
  shirthesis::get_max_min_difference(npv_amount, alignment, reliability_amount, phase)
```


